# Generated by Django 5.1.6 on 2025-02-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='api.tag'),
        ),
    ]
