# Generated by Django 5.1.6 on 2025-02-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_group_album_alter_group_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='icon',
            field=models.ImageField(default='misc/722e64ef8f12418691bf75c04b83ebbe.png', null=True, upload_to='group/'),
        ),
    ]
