# Generated by Django 5.1.6 on 2025-02-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_plan_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='date',
            new_name='end',
        ),
        migrations.AddField(
            model_name='group',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
