# Generated by Django 5.1.6 on 2025-02-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_message_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='icon',
            field=models.ImageField(default='misc/430450-svetik.jpg', null=True, upload_to='group/'),
        ),
    ]
